### ISSUE TITLE
GSIM information object, class, entity? 

### ISSUE THREAD

**Issue by FlavioRizzolo** [UNECE/GSIMRevision#1]
GSIM has used a term "information object" but this is confusing as it often associated with instances - should we change it to be aligned with other standards? For example, during the revision of the GSIM Communication Paper, a comment was made "Class is a term used by UML, the representation language of the GSIM model. In UML, an object is an instance of a class, so the term is confusing for those who know UML."

**Comment by FrancineK** [comment]
**Objects** Represent an entity and the basic building block.
**Class** Blue print of an object.
**Classes**: A template for creating objects and implementing behavior in a system. **In UML, a class represents an object or a set of objects** that share a common structure and behavior. They're represented by a rectangle that includes rows of the class name, its attributes, and its operations. When you draw a class in a class diagram, you're only required to fill out the top row—the others are optional if you'd like to provide more detail.
Source: [LucidChart](https://www.lucidchart.com/pages/what-is-UML-unified-modeling-language)

**Comment by InKyungChoi** [comment]
[Decision (19 Jan. 2021)](https://statswiki.unece.org/pages/viewpage.action?pageId=282330124)
: to change "information object" to "class"

**Comment by FlavioRizzolo** [comment]
Resolution: refer to former **GSIM information object** as **GSIM class**.
