### ISSUE TITLE
High level representation of a proposal of Exchange-Channel  as a transport entity - <constrained by> a Protocol Spec to "exchange(send/receive/Queue" - a <message or product> of type : <Questionnaire >

### ISSUE THREAD

**Issue by krishnan-ambady-ds** [UNECE/GSIMRevision#11]

**Comment by krishnan-ambady-ds** [comment]
![image](https://user-images.githubusercontent.com/80923037/157456438-9e6407f3-66d0-4273-b067-e8e683d4ab9b.png)

**Comment by krishnan-ambady-ds** [comment]
![image](https://user-images.githubusercontent.com/80923037/157473310-1dc75fa9-ece8-4f70-b48d-1ba49495c161.png)

**Comment by InKyungChoi** [comment]
@krishnan-ambady-ds - may I ask you to move this discussion under Issue #5 so that we have all relevant comments in the same place?

**Comment by krishnan-ambady-ds** [comment]
![image](https://user-images.githubusercontent.com/80923037/158292767-c923582f-4c10-44f3-b1ca-a5ebdb25c374.png)

**Comment by krishnan-ambady-ds** [comment]
> 

What is the process of copying to Issue#5
