### ISSUE TITLE
Information management datasets

### ISSUE THREAD

**Issue by Patrik2112** [UNECE/GSIMRevision#12]
This proposal applies to datasets that are included in so called “steady states” / “quality gates” / “checkpoints”. In the production process some datasets could be labled as “checkpoints” or “steady states”.

We have identified a need to collect and structure metadata about a dataset that affect our internal management of datasets. We are considering introducing something we call "information management dataset". The new dataset type would inherit from the "Information Set" in the model, like Dataset and Referential metadataset. The new type could be built with a data structure etc. 

Example of information stored in the information management dataset: 
•	Metadata that supports automated archiving, screening and storing of datasets
•	GDPR related information 
•	If the dataset has information about minors (minor children)
•	The dataset information security classification 
•	Information that could support type of storage type
•	If the dataset contains critical community information
•	Etc.

It would be possible to use the referential metadata part of GSIM to achieve the need we describe above. It feels as referential metadata already has a clear purpose and that there is a point in having a clear separation between internal information management metadata and referential metadata.

**Comment by InKyungChoi** [comment]
Hi Patrik! We have recently started working on this issue. Since this issue is related to referential metadata, we are discussing it together with #6. 
There is an initial attempt to map existing GSIM referential metadata classes to your use case. Feel free to jump in if you see anything missing/mis-interpreated.

**Comment by FlavioRizzolo** [comment]
Merged with issue https://github.com/UNECE/GSIMRevision/issues/6
