### ISSUE TITLE
Missing GSIM class – guidelines, policies and standards

### ISSUE THREAD

**Issue by FlavioRizzolo** [UNECE/GSIMRevision#3]
GSIM lacks descriptions of information objects that are often used to support, inform and guide statistical production. It seems some of them, e.g. methodological handbooks, corporate policies, international standards, national / regional legal requirements, appear often enough in the linking GSBPM and GSIM report to deserve a first-class citizen status in the model.

**Comment by FrancineK** [comment]
From the [Business Rules Group](https://github.com/UNECE/GSIMRevision/issues/3)
![image](https://user-images.githubusercontent.com/24411883/149971155-a67c228f-cd5a-4063-8a47-881da6debf94.png)

**Comment by InKyungChoi** [comment]
[Decision (19 Jan. 2021) ](https://statswiki.unece.org/pages/viewpage.action?pageId=282330124): to create one class with an attribute (controlledVocabulary) for describing different types. Name of class to be decided

**Comment by InKyungChoi** [comment]
How about **Knowledge Source**? See [An Introduction to Decision Modelling with DMN (on page 7)](https://www.omg.org/news/whitepapers/An_Introduction_to_Decision_Modeling_with_DMN.pdf): _Decisions are driven by policies, regulations, best practices, human expertise and analytic insight. DMN calls these Knowledge Sources and they describe how the decision is made and how it uses the Input Data identified._ 

Also question – if we create this, under which GSIM Group it belongs to?

**Comment by FrancineK** [comment]
It would be under Business Group, related to Rule. I suggest we use "Compliance _Framework_" or something about Compliance instead of "Knowledge Source". Knowledge Source is broad term which, in my opinion, can lead to confusion.

**Comment by FlavioRizzolo** [comment]
I like Compliance Framework.

I don't think we need all the sub-classes though. Couldn't just list a few in the definition and/or explanatory text? Unless we use specific sub-classes somewhere else.

**Comment by FrancineK** [comment]
No, we don't need the sub class, a controlled vocabulary should do.

**Comment by FlavioRizzolo** [comment]
Look into ISO Guide 2 and TOGAF for more details.

**Comment by InKyungChoi** [comment]
[GSIM revision team decision (16 Feb. 2022) ](https://statswiki.unece.org/pages/viewpage.action?pageId=282330124): "Knowledge Resource" is too broad, "Compliance Framework" unclear. @zoltanvereczkei to detail his proposal about "Normative Documents"

**Comment by zoltanvereczkei** [comment]
I have the proposal to use the term Normative Documents. Based on the results of a previous ESSnet in the European Statistical System, ESSnet on Standardisation, we organised these objects this way:

[https://ec.europa.eu/eurostat/cros/sites/default/files/nds.png](url)

**Comment by FrancineK** [comment]
I am in agreement with this proposition. The only thing I am wondering is whether to call it a document. I see this more as a **Normative Reference** rather than a document.

**Comment by FranckCo** [comment]
See also the [Profiles Vocabulary](https://w3c.github.io/dx-prof/prof/) for more references about standards, guidelines, etc.

**Comment by InKyungChoi** [comment]
[GSIM revision team decision (9 March 2022)](https://statswiki.unece.org/pages/viewpage.action?pageId=282330124#expand-Meetingnotes10March2022): "Normative" can be confusing as it could mean different things for different people (e.g., something obligatory vs. something to follow to be aligned with standards), perhaps "Reference"? Action:  @zoltanvereczkei to narrow down and make a proposal

**Comment by zoltanvereczkei** [comment]
Based on the discussion we had last time and the comments made, I have the following new proposal for this GSIM class:

Name of the class: normative references.
Defintion: Normative references are those documents that contain material that must be understood and used to implement the standard, so normative references are indispensable when applying the standard. Source: https://standards.ieee.org/faqs/references/

Main sub-classes:

- **Legal acts** (and similar legal obligations) are binding and they set framework/requirements for the production of statistics that are obligatory. 

- **Standards** are those normative references that are very important for statistics. They are by definition not enforced by regulations, standards are to be applied on a voluntary basis. Standards are expected to provide benefits in the following areas:

- **Other normative references**: not as important as standards but still used in the statistical production processes.

**Comment by InKyungChoi** [comment]
[GSIM revision team decision (30 March 2022)](https://statswiki.unece.org/pages/viewpage.action?pageId=282330124#expand-Meetingnotes30March2022): 
Decision: to name the new class as "Reference Documents". In the explanatory text, describe different types, that they can be unstructured and translated into Rules; add that documents can exist in physical, electronic; their content can be formal (e.g., legal acts) or non-formal; format can be formal (e.g., XML) and non-formal. Issue to be closed

**Comment by InKyungChoi** [comment]
As an explanatory text, I would suggest something like: 

"The examples of _Reference Documents_ include: methodological handbooks, standards, legislation, corporate policies/guideline and best practices. _Reference Documents_ are often unstructured and can be translated into _Rules_ (e.g., quality requirements set by legislation can be written as a _Rule_). Note that documents can be physical (e.g., books) or electronical. The documents can be formal in terms of content (e.g., laws) or in terms of format (e.g., XML).

We also need to add a relationship with Rule (maybe "is based on").

**Comment by zoltanvereczkei** [comment]
I know we closed this issue at the last meeting but don't we need subclasses to be defined here (cover those types that are in the current proposal for the class)? There is still a "hidden issue" here: standards cover not only methodological stuff or reference documents but other things (such as IT tools)? This may not be relevant for our work now but I feel that we need to go a bit deeper here. Happy to work on this but if the group finds this unrelevant, just neglect my comment.

**Comment by FlavioRizzolo** [comment]
You have a point. The question is whether that can be covered by the new ReferenceDocument class or not. Let's discuss today.

**Comment by FlavioRizzolo** [comment]
It was decided in the meeting to go with both the proposed definition and explanatory text.
