### ISSUE TITLE
GSIM Exchange Group definition / explanatory text update

### ISSUE THREAD

**Issue by InKyungChoi** [UNECE/GSIMRevision#31]
Under Exchange Group, I think there are three groups that need to be looked at together. 

1. There have been quite many changes to **classes around Exchange Instrument** (formerly, Exchange Channel), there are classes removed (Administrative Register, Protocol, Statistical Register) and added (Register, Exchange Specification). There are so many changes, I made proposals directly on [this google doc](https://docs.google.com/document/d/1tDSSTBLw9Br2NGfI9ILK9x58s8JBykSM/edit#) 
2. **Information Consumer and Information Provider**
   - Metadata Glossary team proposed a new definition: "Agent that consumes disseminated data" (InKyung: if Information Consumer is a type of "Agent", shouldn't this be sub-type of "Agent" (or "Agent in Role", not sub-type of "Role"?))
   - Linking GSBPM-GSIM task team asked if we could “add a note to Information Consumer (on the input side) that it is consumer in a broad sense including the persona”
   - Linking GSBPM-GSIM task team asked to change relationship with “Provision Agreement” from “agrees to” to “subscribes to”

Object |  Definition | Explanatory Text
-- |  -- | --
Information Consumer | ~~Individual or Organization~~ **Agent** that consumes disseminated data | The Information Consumer accesses a set of information **in** ~~via~~ a Product ~~(or potentially via another Exchange Channel)~~ that is made available by Dissemination Component ~~, which contains one or more Presentations~~. The Information Consumer **subscribes to** ~~'s access to the information is subject to~~ a Provision Agreement, which sets out conditions of access. **The Information Consumer can be defined in a broad sense with a persona concept (group of Individuals) without specific details.**  

Object |  Definition | Explanatory Text
-- |  -- | --
Information Provider | ~~Individual or Organization~~ **Agent** that provides collected information. | An Information Provider possesses sets of information (that it has generated, collected, produced, bought or otherwise acquired) and is willing to supply that information (data or referential metadata) to the statistical organization. The two parties use a Provision Agreement to agree on the Data Structure and Referential Metadata Structure of the data ~~to be exchanged via an Exchange Channel~~.
3. **Classes related to Question** which have two comment issues ([raised by metadata glossary team](https://statswiki.unece.org/pages/viewpage.action?pageId=282330852))
    - The explanatory texts are esoteric, concrete examples would be helpful; 
    -  For Instance Question, Instance Question Block and Instance Statement: definition says “use of question in a particular questionnaire” while explanatory text says “use of question in a particular questionnaire component”

**Comment by InKyungChoi** [comment]
Regarding "concrete examples would be helpful" for classes related to Question above: [INSEE seems to have added more classes around Question](https://statswiki.unece.org/pages/viewpage.action?pageId=154042589) and worked on metadata-driven data collection for long, @flo7894 - do you perhaps have some concrete examples that could be used in the explanatory text of Instance Question, Instance Question Block, Instance Question Block, etc.?

**Comment by InKyungChoi** [comment]
(continuing [discussion from the last meeting](https://github.com/UNECE/GSIMRevision/discussions/35)) 
 
**About Maintainer, Owner, Information Consumer being sub-types of Role**

It was initially weird for me that "Maintainer" or "Information Provider" are "Role" (I was thinking Role should be more like "Maintenance" or "Maintain"). I don't know why it felt weird before but now saying something like "I am playing a Role of Maintainer" sounds clear to me. I could not find a formal definition of "Role", but at least a dictionary says it is a "function assumed or played by a person or a thing", so it is implicit already that the role is played by an Agent.

**About an Information Provider "agrees to" Provision Agreement** 

First, I think it is not just Information Provider /  Consumer that agrees on something. Although we don't have other types of agreements in GSIM, I can imagine Maintainer or Owner having some kind of Terms of Reference to agree on. So I think if we want to make Information Provider and Information Consumer as sub-type of Agent In Role (not sub-type of Role) on the basis that Role does not agree on something, we have to make Maintainer, Owner and Contact as sub-type of Agent In Role because they also have agreements or contract. Having said this, I wonder if we cannot really say Role agrees on something. The need of agreeing on the Provision Agreement comes from Role even before any particular Agent coming along to assume the Role, so it is inherited from the Role. 

**About [Definition of Agent](https://docs.google.com/document/d/1UaBbCHFe4opHWmNK4fjh0_luiGL99mM8E4D8JPfmdVw/edit#heading=h.1t3h5sf) and [definition of Agent In Role](https://docs.google.com/document/d/1UaBbCHFe4opHWmNK4fjh0_luiGL99mM8E4D8JPfmdVw/edit#heading=h.4d34og8)  being too similar**: [FOAF Agent](http://xmlns.com/foaf/0.1/#term_Agent) is "things that do stuff" and a dictionary says "a person or thing that takes an active role or produces a specified effect".  So may be we can consider Agent doing (some but unspecified) Role but Agent In Role doing a specified Role? [ is "

**=> In short,** I think we can keep the model as they are but only change definitions of Information Provider (and other Roles) from "Agent that provides information" to "Role of providing information" (perhaps this is what @FrancineK already meant from the beginning :D?).

**Comment by InKyungChoi** [comment]
I have been going through [meeting notes since 2020](https://docs.google.com/document/d/1DBUbq6S_sgyj2aycwZRNdYaxFjt2LSHv/edit) and found that, in 4 November 2020, when we were talking about sub-types of Role in Base Group (Maintainer, Contact), it was proposed to change their definitions to "_Role in which..._".. and to "_When making changes, make sure to do it consistently for Information Provider and Information Consumer too_"

**Comment by FrancineK** [comment]
> (continuing [discussion from the last meeting](https://github.com/UNECE/GSIMRevision/discussions/35))
> 
> **About Maintainer, Owner, Information Consumer being sub-types of Role**
> 
> It was initially weird for me that "Maintainer" or "Information Provider" are "Role" (I was thinking Role should be more like "Maintenance" or "Maintain"). I don't know why it felt weird before but now saying something like "I am playing a Role of Maintainer" sounds clear to me. I could not find a formal definition of "Role", but at least a dictionary says it is a "function assumed or played by a person or a thing", so it is implicit already that the role is played by an Agent.
> 
> **About an Information Provider "agrees to" Provision Agreement**
> 
> First, I think it is not just Information Provider / Consumer that agrees on something. Although we don't have other types of agreements in GSIM, I can imagine Maintainer or Owner having some kind of Terms of Reference to agree on. So I think if we want to make Information Provider and Information Consumer as sub-type of Agent In Role (not sub-type of Role) on the basis that Role does not agree on something, we have to make Maintainer, Owner and Contact as sub-type of Agent In Role because they also have agreements or contract. Having said this, I wonder if we cannot really say Role agrees on something. The need of agreeing on the Provision Agreement comes from Role even before any particular Agent coming along to assume the Role, so it is inherited from the Role.
> 
> **About [Definition of Agent](https://docs.google.com/document/d/1UaBbCHFe4opHWmNK4fjh0_luiGL99mM8E4D8JPfmdVw/edit#heading=h.1t3h5sf) and [definition of Agent In Role](https://docs.google.com/document/d/1UaBbCHFe4opHWmNK4fjh0_luiGL99mM8E4D8JPfmdVw/edit#heading=h.4d34og8) being too similar**: [FOAF Agent](http://xmlns.com/foaf/0.1/#term_Agent) is "things that do stuff" and a dictionary says "a person or thing that takes an active role or produces a specified effect". So may be we can consider Agent doing (some but unspecified) Role but Agent In Role doing a specified Role? (which seems already the case in the current definitions)
> 
> **=> In short,** I think we can keep the model as they are but only change definitions of Information Provider (and other Roles) from "Agent that provides information" to "Role of providing information" (perhaps this is what @FrancineK already meant from the beginning :D?).

Yes, @InKyungChoi, that is what I was getting to.

**Comment by InKyungChoi** [comment]
@FrancineK - so you want Information Consumer / Provider, Owner, etc. to be a sub-type of Agent? not Role?

**Comment by FrancineK** [comment]
> 

@InKyungChoi, my bad. I was looking the explanation text and simply copied the definition. I have corrected in my previous post.

**Comment by FlavioRizzolo** [comment]
I suggest these small editorial changes to the definitions:
- **Information Consumer**: role that entails consuming data and information
- **Information Provider**: role that entails providing data and information

**Comment by FrancineK** [comment]
For Information Provider, in the explanatory text, change Exchange Channel to Exchange Instrument.

**Comment by FlavioRizzolo** [comment]
To be implemented in EA UML
