### ISSUE TITLE
Some remaining questions in Business Group

### ISSUE THREAD

**Issue by InKyungChoi** [UNECE/GSIMRevision#41]
![image](https://user-images.githubusercontent.com/10498769/219695558-382e75ce-61c2-49dd-999c-1be16244ca16.png)

Here is the updated version of Business Group (only around design-level GSIM classes)

### Regarding associations around Business Service

The association (in orange color) between Business Service and Business Process is redundant (because it is covered by Process Step), the same for the association between Business Service and Statistical Program Design (because it is covered by Process Design). Delete? 

### Regarding Process Design

It seems the target of design (Process Design) is at the level of Business Process, not Process Step. The [decision to add an association between Business Process and Process Design](https://docs.google.com/document/d/1rAXFJ6UmgKkuEY_lUSeZbQaTmeFrEi6BtraM46ubUwU/edit#heading=h.4d34og8) as well as new definition ("specification of each Process Step and description of their arrangement in a Business Process needed to perform a Business Function") in this task team also supported this view.

But in practice, I think there are cases where we want to "design" Process Step. Let's say our Business Function is "integrate data" (GSBPM sub-process 5.1), and we want to design a Business Process for that. Then, the Process Design would have multiple Process Steps (e.g., "read in data", "find identifier", "merge via identifier", "check matching rate") and corresponding Process Input Specifications and Process Output Specifications and a Process Control Design (note that Process Design has only one Process Control Design) that controls the flow between above Process Steps. In this case, would it be useful to be able to say certain inputs are for certain Process Step? I guess this might be partially addressed by (new) direct associations between Process Step and Process Input/Output Specification (as in https://github.com/UNECE/GSIMRevision/issues/7), but it seems duplicating to have thess specifications attached for both Process Step and Business Process (unless @FlavioRizzolo meant to remove the associations between specifications and Business Process). Any thoughts?

**Comment by andreapetres** [comment]
Regarding Process Design: 
could adding _Activity_ as a new class with subtypes _Process, Sub-process, Process step, Task_ help? 

This question may come up for most classes in Business Group that refer to some aspect of a _Process_ (e.g. Process Method, Process Input, Process output, Process Metric, etc.) -- they may be relevant at other levels as well (sub-process, process step, etc.), not only for processes.

**Comment by InKyungChoi** [comment]
Decision made (see #43):

- Action: to remove relationship between Process Pattern and Business Function. Process Pattern has at least one Process Design, and Process Design already specifies delivery of Business Function, so relationship between Process Pattern and Business Function is not needed.
- Action: to remove relationship between Change Definition and Population. No reason Population should be highlighted.
- Action: to keep the relationship between Business Process and Process Design. Business Process doesn’t have to have Process Step (optional), so we need to use this relationship (make it “specifies”) between Business Process and Process Design. Also, remove “implemented by” relationship between Process Design and Process Step (there is already “specifies” relationship between two).
- Action: to remove “has context of” relationship between Assessment and Subject Field.
