### ISSUE TITLE
Missing GSIM class – quality indicators

### ISSUE THREAD

**Issue by FlavioRizzolo** [UNECE/GSIMRevision#6]
Quality is an important information that drives the statistical business process. GSBPM Quality Indicator shows all GSBPM sub-processes produce quality information in one form or another and there is no GSIM information object to capture this quality information. Referential Metadata Set might be used for this, but it will make it difficult to differentiate quality from other types of metadata as well as overload Referential Metadata Set.

**Comment by FrancineK** [comment]
A tentative mapping of Referential Metadata
![image](https://user-images.githubusercontent.com/24411883/171252441-ab0e2492-d6d1-4f18-ace0-8a2252a47dcd.png)

- **Referential Metadata Set**:	An organized collection of referential metadata for a given Referential Metadata Subject. 
  Ex: Methodology, Quality
- **Referential Metadata Structure**:	Defines the structure of an organized collection of referential metadata (Referential Metadata Set). 
 Ex: for Methodology, methodology types:
_ERROR_DETECTION, ESTIMATION_COMPILATION, IMPUTATION, VALIDATION, REVISIONS, SAMPLING, ACCURACY, etc._
  Ex: for Quality, six dimensions of quality:
_relevance, accuracy, timeliness, accessibility, interpretability, coherence_ 
- **Referential Metadata Attribute**:	The role given to a Represented Variable to supply information in the context of a Referential Metadata Structure.
 Ex. Quality Indicator, Status Flag, Methodology Description, Quality Statement, etc., 
- **Referential Metadata Subject**:	Identifies the subject of an organized collection of referential metadata.
  Ex. DataSet, Represented Variable, Data Point 
- **Referential Metadata Subject Item**:	Identifies the actual subject for which referential metadata is reported.
 Ex. Sampling Frame (DataSet), Population Count (Value in Data Point)
- **Referential Metadata Content Item**:	The content describing a particular characteristic of a Referential Metadata Subject.

**Comment by JALinnerud** [comment]
As far as I remember the referential metadata classes originated from reference metadata classes in SDMX. See https://raw.githubusercontent.com/UKGovLD/publishing-statistical-data/master/specs/src/main/vocab/sdmx-attribute.ttl These also relate to SIMS (Single Integrated Metadata Structure) used to report quality to Eurostat. We are not currently using SIMS for our quality declarations, but we are looking into using it.

**Comment by FrancineK** [comment]
> Why are the desciptions, names and text only in Bilingual text? Shoukdn't they be multilingual?

Yes, we will need to rework this model. This was done for StatCan internal use.

**Comment by InKyungChoi** [comment]
Use case: [Reference Metadata in ESS Standard for Quality Reports Structure (ESQRS)](https://ec.europa.eu/eurostat/cache/metadata/EN/employ_esqrs.htm)

**Comment by InKyungChoi** [comment]
## **Mapping of GSIM referential metadata area for the [ESS Standard for Quality Reports Structure (ESQRS)](https://ec.europa.eu/eurostat/cache/metadata/EN/employ_esqrs.htm) and[ Information Management Set (GSIM Issue from Sweden)](https://github.com/UNECE/GSIMRevision/issues/12)**

![image](https://user-images.githubusercontent.com/10498769/185107256-c2a02289-a1c3-4b38-a61d-8a04d03152a4.png)


## **Issues:** 
1. [Referential Metadata Subject ](https://statswiki.unece.org/display/clickablegsim/Referential+Metadata+Subject)is currently constrained by Value Domain. Its explanatory text says "GSIM object type may be Product for which there is a list specified in a Value Domain. The Value Domain specifies the list of actual Products for which reference metadata can be reported or authored using this Referential Metadata Structure." but I think creating a list to be able to refer to a subject of referential metadata is too much 
-> potential solution: i) Add a relationship with several typical subjects such as Questionnaire, Statistical Program, Data Set; ii)
Add a relationship between  Referential Metadata Subject and Identifiable Artefact 
2. [Referential Metadata Attribute](https://statswiki.unece.org/display/clickablegsim/Referential+Metadata+Attribute?src=contextnavpagetreemode) is currently "defined by" Represented Variable. Although cardinality is 0,1, but its definition "role given to a Represented Variable to supply information in the context of a Referential Metadata Structure" seems to imply that it is not optional
-> potential solution: Change definition (e.g., "characteristic providing qualitative information for a given Referential Metadata Subject") and remove relationship with Represented Variable

## **As a reference, see how it is done in SDMX:** 
![image](https://user-images.githubusercontent.com/10498769/185107400-a441f13a-1be5-4e41-9994-7099899c5b32.png)

**Comment by InKyungChoi** [comment]
Another mapping example for a documentation of statistical register (from [Istat's MWW2022 presentation](https://unece.org/sites/default/files/2022-07/MWW2022_Presentation_Italy_Simeoni.pdf))
![image](https://user-images.githubusercontent.com/10498769/185442608-1bec65b9-ed6c-4d83-9967-b436f2653758.png)

**Comment by InKyungChoi** [comment]
## Updated model
(based on discussion in #22)
![image](https://user-images.githubusercontent.com/10498769/188093579-47d15029-40af-4dc8-942f-b35f4620e3cb.png)

**Some remarks:** 
- For now, subjects are kept in the model to see how it works as proposed in the last meeting. Removing RM Subject and RM Subject Item has the benefit of simplifying the model, but it might be worth keeping it to make it clear what subject is..? 
- The relationship between RM Structure and RM Attribute used to be composition - but can it be aggregation so that we can re-use RM Attributes not just in the context of certain RM Structure. 
- Represented Variable is now removed from the picture, but I wonder if we could also link RM Attribute with Idenfiable Artefect? 

## Proposed definition / explanatory text
- **Referential Metadata Subject**
   - Definition: subject for which an organised collection of referential metadata is reported
   - Explanatory text: Referential Metadata Subject identifies the subject of the metadata that can be reported using this Referential Metadata Structure. These subjects may be any GSIM class on which organised set of metadata is needed, such as Statistical Program, Data Set, Statistical Classification.

- **Referential Metadata Structure**
   - Definition: structure of an organised collection of referential metadata
   - Explanatory text: Referential Metadata Structure defines a structured list of Referential Metadata Attributes for a given Referential Metadata Subject (e.g., ESS Standard for Quality Reports Structure)
 
- **Referential Metadata Attribute**
   - Definition: particular characteristic of referential metadata OR characteristic that describes or qualifies Referential Metadata Subject (!! note that this definition is completely different from [original definition](https://statswiki.unece.org/display/clickablegsim/Referential+Metadata+Attribute), feel free to propose a new one!)
   - Explanatory text: A set of Referential Metadata Attributes is structured by Referential Metadata Structure to describe Referential Metadata Subject. Examples of Referential Metadata Attributes can be Represented Variable (e.g., "Accuracy", "Timeliness" when describing quality information) or other GSIM class (e.g., Statistical Classification, Contact, Owner)

- **Referential Metadata Content**
  - Definition: actual content describing Referential Metadata Attribute 
   - Explanatory text: Referential Metadata Content can take different formats (e.g., text, number, value from a predefined codelist, table)
   - 
- **Referential Metadata Subject Item**
  - Definition: actual subject for which referential metadata is reported
   - Explanatory text: Examples are an actual Product such as Balance of Payments and International Investment Position, Australia, June 2013, or a collection of Data Points such as the Data Points for a single region within a Data Set covering all regions for a country.

**Comment by InKyungChoi** [comment]
I found an old GSIM discussion (from 2018) that has very different interpretations...!!! https://statswiki.unece.org/pages/viewpage.action?pageId=129177198

It seems, in short, 
1) Referential Metadata (RM) parts were applied (or originally, primarily aimed to be applied) to footnotes of tables (using table footnote as RM Attribute - which actually got me even more confused about how Represented Variable plays a role here...) 
2) it got too complicated; 
3) Guillaume suggested "A MetadataStructureDefinition structures a MetadataFlowDefinition and contains one or more MetadataTarget composed of TargetObject. So basically it is a heap of metadata atttributes gathered in a set that targets a flow." which is more similar to what we discussed, and pointed out "The problem in this example is that we are mixing the DataStructure and the MetadataStructure areas without being as complete as the SDMX-IM on the MetadataStructure/Set part"; 
4) but the way he applied RM to Single Integrated Metadata Structure (SIMS) is quite different...
5) in the end, [there were no big changes made to this part] in new version of GSIM (https://statswiki.unece.org/display/gsim/GSIM+v1.2+main+changes) (except "Self-referential relationship name changed from parent/child to parent-child")

@JALinnerud - what do you think? Do you think we are deviating too much from what was originally aimed? 
@FrancineK - do you think the new way we use can be applied to footnotes? 

If we cannot apply RM to footnotes, we cannot do what we could do before - but to be honest, I am not sure if it COULD do before....?

**Comment by FrancineK** [comment]
> 
Hi @InKyungChoi, I tried to work it out with this page: https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3210000101&request_locale=en. 
The **Referential Metadata Set**: 
- **Frequency**, **Dataset ID**, **Release date** (these are variables come from Data Structure) and **Classification (Geography)** (this is the identifier component), and **Footnotes** (Referential Metadata ONLY).
If I was to consider **Footnotes** only:
- Referential Metadata Set: Footnotes
- Referential Metadata Structure: Table Footnote: Footnote1, Footnote2, etc.
- Referential Metadata Attribute: 
-- Footnote1 statement
-- **_What about Frequency, Dataset ID, Release date which are variables? Could this have referenced by the link to Represented Variable_**?
- Referential Metadata Subject:  Dataset : Stocks of specified dairy products
- Referential Metadata Subject Item: Stocks of specified dairy products with ID 32-10-0001-01
- Referential Metadata Content Item: Footnote1 actual statement: As of January 1988 Newfoundland and Labrador stocks are included.

I hope I am making sense and also answering your question.

**Comment by InKyungChoi** [comment]
Updated (relationship between RM Attribute and IA introduced based on meeting notes October 5 #27)

![image](https://user-images.githubusercontent.com/10498769/198271253-774cbb69-e443-411f-a9e5-9b52b8f2160f.png)

**Comment by FrancineK** [comment]
Hopefully, this will finally answer the question!!

![image](https://user-images.githubusercontent.com/24411883/202060620-ba0a3b2b-a02f-43f3-a840-81bc8c83e1b9.png)

**Comment by InKyungChoi** [comment]
About Referential Metadata (RM) Subject Item in the [example of StatCan "Nursing and residential care facilities" table](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1310082801). 

When a subject is a single Represented Variable, we can say RM Subject is a "Total Residents" (with RM Attribute being a footnote and RM Content Item being a particular footnote #5), can we also still say RM Subject Item is "Total Residents" BUT used in the context of a particular data set? Hence RM Subject Item is indeed Instance Variable? 

Because, "Total Residents" would already exist as a represented variable, for example, in a variable catalog. But when we use this variable in this particular table "Nursing and residential care facilities", we attach this particular footnote #5 this the variable.

**Comment by flo7894** [comment]
With the lastest modelisation there seems to be no link between a ReferentialMetadataSet and its content which consist of ReferentialMetadataContentItem. Also the composition relation between ReferentialMetadataContentItem et ReferentialMetadataAttribute seems odd, shouldn't a ReferentialMetadataContentItem to be viewed as an instance of a ReferentialMetadataAtrribute in the context of a particular IdentifiableArtefact.

**Comment by FrancineK** [comment]
> With the lastest modelisation there seems to be no link between a ReferentialMetadataSet and its content which consist of ReferentialMetadataContentItem. Also the composition relation between ReferentialMetadataContentItem et ReferentialMetadataAttribute seems odd, shouldn't a ReferentialMetadataContentItem to be viewed as an instance of a ReferentialMetadataAtrribute in the context of a particular IdentifiableArtefact.

You are right @flo7894, on both points. The first one was not obvious to me at first, but I think that the link between Attribute with ContentItem as an intance is what was missing from the original model.

**Comment by InKyungChoi** [comment]
![image](https://user-images.githubusercontent.com/10498769/215720073-59d65d19-1e16-405b-9a5d-1f05dd59ccd4.png)


Object |  Definition | Explanatory Text
-- |  -- | --
Referential Metadata Structure | structure of an organised collection of referential metadata | A Referential Metadata Structure defines a structured list of Referential Metadata Attributes for a given Referential Metadata Subject. Examples of Referential Metadata Structure include structures for describing quality information and methodologies information (e.g., ESS Standard for Quality Reports Structure) or characteristics of registers as well as a structure of documentation storing information necessary for internal dataset management (e.g., GDPR status, existence of information on minor)
Referential Metadata Set | organised collection of referential metadata for a given Referential Metadata Subject | Each Referential Metadata Set uses a Referential Metadata Structure to define a structured list of Referential Metadata Attributes for a given Referential Metadata Subject.
Referential Metadata Attribute | characteristic that describes or qualifies Referential Metadata Subject | A set of Referential Metadata Attributes is structured by Referential Metadata Structure to describe Referential Metadata Subject. Examples of Referential Metadata Attributes can be Represented Variable (e.g., "Accuracy", "Timeliness" when describing quality information) or other GSIM class (e.g., Statistical Classification, Contact, Owner).
Referential Metadata Subject | subject for which an organised collection of referential metadata is reported | The Referential Metadata Subject identifies the subject of the metadata that can be reported using this Referential Metadata Structure. These subjects may be any GSIM class on which organised set of metadata is needed, such as Statistical Program, Data Set, Questionnaire and Statistical Classification.
Referential Metadata Subject Item | actual subject for which referential metadata is reported | Examples are an actual Product such as Balance of Payments and International Investment Position, Australia, June 2013, or a collection of Data Points such as the Data Points for a single region within a Data Set covering all regions for a country.
Referental Metadata Content Item | actual content for Referential Metadata Attribute | Referential Metadata Content Item can take different formats (e.g., text, number, value from a predefined codelist, table)

**Comment by FlavioRizzolo** [comment]
I haven't finished reviewing the whole thing, but I noticed that **Referential Metadata Attribute** is missing the optional "is defined by" association to **Represented Variable**. I think we still need that for two reasons: (i) the **Referential Metadata Attribute** parallels the **Attribute Component** in **Data Structures**, and (ii) in many cases we could use a **Represented Variable**, as your last example shows.

**Comment by FrancineK** [comment]
![image](https://user-images.githubusercontent.com/24411883/216060728-2010680f-5639-4cf1-9ba5-246b9d14b5d1.png)
If Content Item is an instance of Attribute, is the **parent-child** relationship justified for Content Item?

**Comment by flo7894** [comment]
A _ReferentialMetadataSubject_ refers to a GSIM class e.g. _Dataset_ whereas a _ReferentialMetadataSubjectItem_ refers to an instance of _Dataset_ e.g. "Nursing facilities, total resident by annual (2020)". The _IdentifiableArtefact_ seems to more likely to be the instance of _Dataset_. May be the "refers to" property should be between _IdentifiableArtefact_ and _ReferentialMetadataSubjectItem_ or _ReferentialMetadataCoreItem_ ?


> Questions:
> 
>     1. Does this work? (still not clear how to do for a situation where Subject is a data table and certain footnotes (Attributes) are for the entire data table while others are for Represented Variable inside the table)
> 

Regarding question 1, couldn't we consider having a _ReferentialMetadataSet_ for the entire data table and others _ReferentialMetadataSet_ for the _RepresentedVariable_s ,  then  you would group them together with the _DataSet_ in an _InformationSet_ . Thus the _Product_ using the _InformationSet_ gets all the footnotes ?

**Comment by InKyungChoi** [comment]
@flo7894 
> A _ReferentialMetadataSubject_ refers to a GSIM class e.g. _Dataset_ whereas a _ReferentialMetadataSubjectItem_ refers to an instance of _Dataset_ e.g. "Nursing facilities, total resident by annual (2020)". The _IdentifiableArtefact_ seems more likely to be the instance of _Dataset_. May be there should not be a "refers to" property between _IdentifiableArtefact_ and _ReferentialMetadataSubject_ ?

=> _DataSet_ is a sub-type of _IndentifiableArtefact_, and many of existing GSIM classes that can be _ReferentialMetadataSubject_ are sub-types of _IndentifiableArtefact_ (e.g., _StatisticalClassification_, _StatisticalProgram_). I think this creates more confusion :( 

> Regarding question 1, couldn't we consider having a _ReferentialMetadataSet_ for the entire data table and others _ReferentialMetadataSet_ for the _RepresentedVariable_s , then you would group them together with the _DataSet_ in an _InformationSet_ . Thus the _Product_ using the _InformationSet_ gets all the footnotes ?

=> this works for me!

**Comment by InKyungChoi** [comment]
![image](https://user-images.githubusercontent.com/10498769/219090927-dd34bb86-c781-4228-899a-383abf8a245c.png)

**Comment by FrancineK** [comment]
Change link from Subject to Identifiable Artifact to Subject Item to Id. Art. And Add an attribute to Subject to indicate that it is any GSIM Information Class.

**Comment by FlavioRizzolo** [comment]
To be implemented in EA UML
